### ISSUE TITLE
Can not get the results in the paper

### ISSUE THREAD

**Issue by jiayeleng** [WinKawaks/SketchDreamer#2]
Hello, I am trying to run your code in QuickDraw dataset, but I find the results look a little weird. Like the "a_simple_drawing_of_an_apple", there are some extra lines that don't match the apple, so if I should reduce the stroke numbers?

**Comment by jiayeleng** [comment]
![my_apple1](https://github.com/WinKawaks/SketchDreamer/assets/50299502/2a96f4fc-9598-4543-8e91-498f1181361b)
![iter1000](https://github.com/WinKawaks/SketchDreamer/assets/50299502/8638e041-0655-4ca8-931a-17a721d32d36)
Here are my input and output, I use the default setting, with 16 strokes, 5 segments, and 1001 iterations.

**Comment by jiayeleng** [comment]
![test](https://github.com/WinKawaks/SketchDreamer/assets/50299502/265207d8-a7f5-4a6f-807e-e8d229372dc2)
The above input is wrong, here is my real input.

**Comment by WinKawaks** [comment]
@jiayeleng The Stable Diffusion model is better at complementing sketches than polishing sketches. And most QuickDraw sketches are too abstract and may not work well as the conditions of ControlNet. Could you use some other examples (incomplete sketches) with larger stroke widths? It seems to me that your input is already a complete apple.
